---
- name: Restart blackbox_exporter
  become: true
  systemd:
    daemon_reload: true
    name: blackbox_exporter
    state: restarted

- name: Reload blackbox_exporter
  become: true
  systemd:
    name: blackbox_exporter
    state: reloaded
