- name: Check if additional disk exists
  stat:
    path: "{{ device_path }}"
  register: device_status
  tags: ['add_disk']

- import_tasks: add_disk.yml
  when: device_status.stat.exists
  tags: ['add_disk']

