---
- name: Start and enable firewalld
  systemd:
   state: started
   name: firewalld
   enabled: yes

- name: allow ssh service
  firewalld:
    zone: public
    service: ssh
    permanent: true
    state: enabled
    immediate: true

- name: Allow metrics ports
  firewalld:
    zone: public
    port: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: true
  with_items:
    - 19000-19100/tcp
